### ISSUE TITLE
Database creation step on Windows can be failing?

### ISSUE THREAD

**Issue by iokinpardo** [nunodonato/workspaice#3]
Hi Nuno,

During installation process under **Windows** system all steps go fine but can you confirm those ones?

- **touch database/database.sqlite**    -   has required , **New-Item -ItemType File -Path .\database\database.sqlite**     for Windows in order to create the database.
- **php artisan migrate:fresh**   -    displays below image. Do I need to answer with "no"? below image corresponds to "**no**" option with  WARN  Command cancelled.

![image](https://github.com/user-attachments/assets/4cfccc1b-a5fb-4b29-83ca-01d90f707763)

In case answering with "**yes**", this is the error I get:

![image](https://github.com/user-attachments/assets/ecafac43-eacc-4284-9522-4abe90154735)

- **php artisan serve**    -    Geting below logs but **Error 500** in the browser but probably those are due to previous **database not being created correctly**, right?

![image](https://github.com/user-attachments/assets/61ff38e8-50e0-4ca7-991e-64a6e1d8f6e1)

![image](https://github.com/user-attachments/assets/9ab363f8-1b2f-4171-80f1-f29b3df8767f)

**Comment by nunodonato** [comment]
Yes the server error is due to missing the database.
Try changing the .env file and specify the full path to the sqlite file.
The warning message is fine to skip, but you can change the environment setting to 'local' in the `.env` file in order to not see the message again.

**Comment by nunodonato** [comment]
PS - if you have a running MySQL DB, you can also change to use that instead of sqlite

**Comment by iokinpardo** [comment]
Many thanks Nuno. 

I got it working under my Linux instance after adjusting the DB_DATABASE= with full path to the sqlite file.

![image](https://github.com/user-attachments/assets/bbac8cda-d01d-427c-bb23-86b54642240e)
