### ISSUE TITLE
Missing rompts/system.txt

### ISSUE THREAD

**Issue by iokinpardo** [nunodonato/workspaice#4]
It seems that the Project is not being able to process any query sent. It says that **workspaice/storage/app/prompts/system.txt** file is not existing. And I can confirm that it is not there. In the **Github** repo there is nothing about it neither the "**prompts**" folder.

Am I mising something to apply?

![image](https://github.com/user-attachments/assets/50fefdee-1689-47c7-bbe8-653ee4c769bc)

![image](https://github.com/user-attachments/assets/6efc97f7-d25c-4c91-ba04-656947f4555c)

![image](https://github.com/user-attachments/assets/b90427ca-36ed-4dc2-ba92-ba876d74a4b3)

**Comment by nunodonato** [comment]
good find! fixed it
